lib/rumbl_web/router.ex
defmodule RumblWeb.Router do
  use RumblWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RumblWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RumblWeb do
    pipe_through :browser # Use the default browser stack

    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", RumblWeb do
  #   pipe_through :api
  # end
end

lib/rumbl/accounts/accounts.ex
defmodule Rumbl.Accounts do
  @moduledoc """
  The Accounts context.
  """

  alias Rumbl.Accounts.User
  alias Rumbl.Repo

  def get_user(id) do
    Repo.get(User, id)
  end

  def get_user!(id) do
    Repo.get!(User, id)
  end

  def get_user_by(params) do
    Repo.get_by(User, params)
  end

  import Ecto.Query

  def get_user_by_email(email) do
    from(u in User, join: c in assoc(u, :credential), where: c.email == ^email)
    |> Repo.one()
    |> Repo.preload(:credential)
  end

  def authenticate_by_email_and_pass(email, given_pass) do
    user = get_user_by_email(email)

    cond do
      user && Comeonin.Pbkdf2.checkpw(given_pass, user.credential.password_hash) ->
        {:ok, user}

      user ->
        {:error, :unauthorized}

      true ->
        Comeonin.Bcrypt.dummy_checkpw()
        {:error, :not_found}
    end
  end

  def list_users do
    Repo.all(User)
  end

  def change_user(%User{} = user) do
    User.changeset(user, %{})
  end

  def create_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end

  def register_user(attrs \\ %{}) do
    %User{}
    |> User.registration_changeset(attrs)
    |> Repo.insert()
  end

end

lib/rumbl/accounts/credential.ex
defmodule Rumbl.Accounts.Credential do
  use Ecto.Schema
  import Ecto.Changeset

  schema "credentials" do
    field :email, :string
    field :password, :string, virtual: true
    field :password_hash, :string
    belongs_to :user, Rumbl.Accounts.User

    timestamps()
  end

  @doc false
  def changeset(credential, attrs) do
    credential
    |> cast(attrs, [:email, :password])
    |> validate_required([:email, :password])
    |> validate_length(:password, min: 6, max: 100)
    |> unique_constraint(:email)
    |> put_pass_hash()
  end

  defp put_pass_hash(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
        put_change(changeset, :password_hash, Comeonin.Pbkdf2.hashpwsalt(pass))
      _ ->
        changeset
    end
  end
end

lib/rumbl/accounts/user.ex
defmodule Rumbl.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset


  alias Rumbl.Accounts.Credential

  schema "users" do
    field :name, :string
    field :username, :string
    has_one :credential, Credential

    timestamps()
  end

  def registration_changeset(user, params) do
    user
    |> changeset(params)
    |> cast_assoc(:credential, with: &Credential.changeset/2, required: true)
  end

  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :username])
    |> validate_required([:name, :username])
    |> validate_length(:username, min: 1, max: 20)
  end
end

lib/rumbl/application.ex
defmodule Rumbl.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Rumbl.Repo,
      # Start the endpoint when the application starts
      RumblWeb.Endpoint,
      # Starts a worker by calling: Rumbl.Worker.start_link(arg)
      # {Rumbl.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Rumbl.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    RumblWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/rumbl/repo.ex
defmodule Rumbl.Repo do
  use Ecto.Repo,
    otp_app: :rumbl,
    adapter: Ecto.Adapters.Postgres
end

lib/rumbl_web/controllers/page_controller.ex
defmodule RumblWeb.PageController do
  use RumblWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/rumbl_web/controllers/session_controller.ex
defmodule RumblWeb.SessionController do
  use RumblWeb, :controller

  def new(conn, _) do
    render(conn, "new.html")
  end

  def create(conn, %{"session" => %{"email" => email, "password" => pass}}) do
    case RumblWeb.Auth.login_by_email_and_pass(conn, email, pass) do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, _reason, conn} ->
        conn
        |> put_flash(:error, "Invalid email/password combination")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> RumblWeb.Auth.logout()
    |> put_flash(:info, "You are now logged out!")
    |> redirect(to: Routes.page_path(conn, :index))
  end
end

lib/rumbl_web/controllers/user_controller.ex
defmodule RumblWeb.UserController do
  use RumblWeb, :controller

  alias Rumbl.Accounts
  alias Rumbl.Accounts.User

  def index(conn, _params) do
    case authenticate(conn) do
      %Plug.Conn{halted: true} = conn ->
        conn

      conn ->
        users = Accounts.list_users()
        render(conn, "index.html", users: users)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user(id)
    render(conn, "show.html", user: user)
  end

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        conn
        |> RumblWeb.Auth.login(user)
        |> put_flash(:info, "#{user.name} created!")
        |> redirect(to: Routes.user_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  defp authenticate(conn) do
    if conn.assigns.current_user do
      conn
    else
      conn
      |> put_flash(:error, "You must be logged in to access that page")
      |> redirect(to: Routes.page_path(conn, :index))
      |> halt()
    end
  end
end

lib/rumbl_web/views/error_view.ex
defmodule RumblWeb.ErrorView do
  use RumblWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/rumbl_web/views/layout_view.ex
defmodule RumblWeb.LayoutView do
  use RumblWeb, :view
end

lib/rumbl_web/views/page_view.ex
defmodule RumblWeb.PageView do
  use RumblWeb, :view
end

lib/rumbl_web/views/session_view.ex
defmodule RumblWeb.SessionView do
  use RumblWeb, :view
end

lib/rumbl_web/views/user_view.ex
defmodule RumblWeb.UserView do
  use RumblWeb, :view

  alias Rumbl.Accounts

  def first_name(%Accounts.User{name: name}) do
    name
    |> String.split(" ")
    |> Enum.at(0)
  end
end

lib/rumbl_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, shrink-to-fit=no, user-scalable=no"/>
    <title>Rumbl · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container"> <nav role="navigation">
      <ul>
        <%= if @current_user do %>
          <li><%= @current_user.username %></li>
          <li><%= link "Log out", to: Routes.session_path(@conn, :delete, @current_user), method: "delete" %></li>
        <% else %>
          <li><%= link "Register", to: Routes.user_path(@conn, :new) %></li>
          <li><%= link "Log in", to: Routes.session_path(@conn, :new) %></li>
      <% end %> </ul>
      </nav>
      <a href="http://phoenixframework.org/" class="phx-logo">
        <img src="<%= Routes.static_url(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
      </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/rumbl_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Rumbl.io" %></h1>
  <p>Rumbl out loud.</p>
</section>

lib/rumbl_web/templates/session/new.html.eex
<h1>Login</h1>
<%= form_for @conn, Routes.session_path(@conn, :create), [as: :session], fn f -> %>
  <div><%= text_input f, :email, placeholder: "Email" %></div>
  <div><%= password_input f, :password, placeholder: "Password" %></div>
  <%= submit "Log in" %>
<% end %>

lib/rumbl_web/templates/user/index.html.eex
<h1>Listing Users</h1>
<table>
  <%= for user <- @users do %>
  <tr>
    <td><%= render "user.html", user: user %></td>
    <td><%= link "View", to: Routes.user_path(@conn, :show, user.id) %></td>
  </tr>
  <% end %>
</table>

lib/rumbl_web/templates/user/new.html.eex
<h1>New User</h1>
<%= form_for @changeset, Routes.user_path(@conn, :create), fn f -> %>
    <%= if @changeset.action do %>
        <div class="alert alert-danger">
            <p>Oops, something went wrong! Please check the errors below.</p>
        </div>
    <% end %>
    <div>
      <%= text_input f, :name, placeholder: "Name" %>
      <%= error_tag f, :name %>
    </div>
    <div>
      <%= text_input f, :username, placeholder: "Username" %>
      <%= error_tag f, :username %>
    </div>
    <div>
        <%= inputs_for f, :credential, fn cf -> %>
            <%= text_input cf, :email, placeholder: "Email" %>
            <%= error_tag cf, :email %>
            <%= password_input cf, :password, placeholder: "Password" %>
            <%= error_tag cf, :password %>
        <% end %>
    </div>
    <%= submit "Create User" %>
<% end %>

lib/rumbl_web/templates/user/show.html.eex
<h1>Showing User</h1>
<%= render "user.html", user: @user %>

lib/rumbl_web/templates/user/user.html.eex
<strong><%= first_name(@user) %></strong> (<%= @user.id %>)